services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - '.env'
    restart: unless-stopped
    networks:
      - dockernet
networks:
  dockernet:
    external: true
